# Generated by Django 4.2 on 2023-04-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_comment_blog_commen_created_0e6ed4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tanks', 'Танки'), ('Hill', 'Хилы'), ('DD', 'ДД'), ('Merchants', 'Торговцы'), ('Guildmaster', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmith', 'Кузнецы'), ('Leatherman', 'Кожевники'), ('Potionist', 'Зельевары'), ('SpellMaster', 'Мастера заклинаний')], default=None, max_length=15)),
                ('posts', models.ManyToManyField(to='blog.post')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category'),
        ),
    ]
