# Generated by Django 4.2 on 2023-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_category_posts_alter_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Hill', 'Хилы'), ('DD', 'ДД'), ('Merchants', 'Торговцы'), ('Guildmaster', 'Гилдмастеры'), ('Questgivers', 'Квестгиверы'), ('Blacksmith', 'Кузнецы'), ('Leatherman', 'Кожевники'), ('Potionist', 'Зельевары'), ('SpellMaster', 'Мастера заклинаний')], default=None, max_length=250),
        ),
    ]
